services:
  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=next
      - POSTGRES_PASSWORD=next1234
      - POSTGRES_DB=next
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  db2:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=next2
      - POSTGRES_PASSWORD=next1234
      - POSTGRES_DB=next2
    ports:
      - '5434:5432'
    volumes:
      - postgres_data2:/var/lib/postgresql/data

volumes:
  postgres_data:
  postgres_data2: